"A datetime string with format 'Y-m-d H:i:s', e.g. '2018-05-23 13:43:32'."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Query {
    # --- BUS ---
    # Ambil semua bus
    buses: [Bus!]! @field(resolver: "App\\GraphQL\\Queries\\BusesResolver")

    # Ambil satu bus berdasarkan ID
    bus(id: ID! @eq): Bus @field(resolver: "App\\GraphQL\\Queries\\BusResolver")

    # --- ROUTE ---
    # Ambil semua route
    routes: [Route!]! @field(resolver: "App\\GraphQL\\Queries\\RoutesResolver")

    # Ambil satu route berdasarkan ID
    route(id: ID! @eq): Route @field(resolver: "App\\GraphQL\\Queries\\RouteResolver")
}

type Mutation {
    # --- MUTATION (TAMBAH DATA) ---
    # Menambah Bus Baru
    addBus(
        code: String!
        capacity: Int!
        route_id: ID!
    ): Bus! @field(resolver: "App\\GraphQL\\Mutations\\AddBusMutation")

    # Menambah Rute Baru
    addRoute(
        name: String!
        origin: String!
        destination: String!
    ): Route! @field(resolver: "App\\GraphQL\\Mutations\\AddRouteMutation")
}

type Bus {
    id: ID!
    code: String!
    capacity: Int!
    route_id: Int!
    
    # Relasi: Bus punya satu Route (Resolver Integrasi)
    route: Route @field(resolver: "App\\GraphQL\\Resolvers\\BusRouteResolver")
}

type Route {
    id: ID!
    name: String!
    origin: String!
    destination: String!

    # Relasi: Route punya banyak Bus (Resolver Integrasi)
    buses: [Bus!]! @field(resolver: "App\\GraphQL\\Resolvers\\RouteBusesResolver")
}