"A datetime string with format 'Y-m-d H:i:s'."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Query {
    buses: [Bus!]! @all
    bus(id: ID! @eq): Bus @find
}

type Mutation {
    # Create (Sama seperti yang berhasil kamu tes)
    addBus(
        code: String!
        capacity: Int!
        route_id: Int!
        lat: Float
        lng: Float
    ): Bus! @create

    # Update (Tanda seru ! dihapus supaya bisa edit sebagian data saja)
    updateBus(
        id: ID! @eq
        code: String
        capacity: Int
        route_id: Int
        lat: Float
        lng: Float
    ): Bus! @update

    # Delete
    deleteBus(id: ID! @eq): Bus @delete
}

type Bus {
    id: ID!
    code: String!
    capacity: Int!
    route_id: Int!
    lat: Float
    lng: Float
    created_at: DateTime!
    updated_at: DateTime!
}