"A datetime string with format 'Y-m-d H:i:s'."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type Query {
    rutes: [Rute!]! @all
    rute(id: ID! @eq): Rute @find
}

type Mutation {
    # Create
    createRute(
        name: String! @rename(attribute: "nama_rute")
        origin: String! @rename(attribute: "titik_awal")
        destination: String! @rename(attribute: "titik_akhir")
        jadwal: String 
    ): Rute! @create

    # Update
    # Perhatikan: @rename TETAP DIPAKAI disini agar Lighthouse tahu kolom mana yang diedit
    updateRute(
        id: ID! @eq
        name: String @rename(attribute: "nama_rute")
        origin: String @rename(attribute: "titik_awal")
        destination: String @rename(attribute: "titik_akhir")
        jadwal: String
    ): Rute! @update

    # Delete
    deleteRute(id: ID! @eq): Rute @delete
}

type Rute {
    id: ID!
    name: String! @rename(attribute: "nama_rute")
    origin: String! @rename(attribute: "titik_awal")
    destination: String! @rename(attribute: "titik_akhir")
    # Output sebagai Object, Input sebagai String (JSON)
    jadwal: Jadwal 
    halte: [Halte!]! @hasMany
    created_at: DateTime!
    updated_at: DateTime!
}

type Jadwal {
    catatan: String
    rute_teks: String
    headway_teks: String
    jam_operasional: String
    jam_operasional_minggu: String
}

type Halte {
    id: ID!
    nama_halte: String!
    urutan: Int!
    created_at: DateTime!
    updated_at: DateTime!
}